import cv2
import numpy as np
import matplotlib.pyplot as plt

img1 = cv2.imread('mandrill.tif',cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread('clown.tif',cv2.IMREAD_GRAYSCALE)
dft1 = cv2.dft(np.float32(img1),flags = cv2.DFT_COMPLEX_OUTPUT)
dft_shift1 = np.fft.fftshift(dft1)

dft2 = cv2.dft(np.float32(img2),flags = cv2.DFT_COMPLEX_OUTPUT)
dft_shift2 = np.fft.fftshift(dft2)
phase_spectrum1 = cv2.phase(dft_shift1[:,:,1],dft_shift1[:,:,0])
magnitude_spectrum1 = cv2.magnitude(dft_shift1[:,:,0],dft_shift1[:,:,1])
magnitude_spectrum11 = 20*np.log(1+np.abs(cv2.magnitude(dft_shift1[:,:,0],dft_shift1[:,:,1])))

phase_spectrum2 = cv2.phase(dft_shift2[:,:,1],dft_shift2[:,:,0])
magnitude_spectrum2 = cv2.magnitude(dft_shift2[:,:,0],dft_shift2[:,:,1])
magnitude_spectrum22 = 20*np.log(1+np.abs(cv2.magnitude(dft_shift2[:,:,0],dft_shift2[:,:,1])))

img_dft1 = np.zeros((256,256,2),dtype = np.float32)
img_dft1[:, :, 0], img_dft1[:, :, 1] = cv2.polarToCart(magnitude_spectrum1,phase_spectrum2)
img_combined1 = cv2.idft(img_dft1)
magnitude1= cv2.magnitude(img_combined1[:, :, 0],img_combined1[:, :, 1])

img_dft2 = np.zeros((256,256,2),dtype = np.float32)
img_dft2[:, :, 0], img_dft2[:, :, 1] = cv2.polarToCart(magnitude_spectrum2,phase_spectrum1)
img_combined2 = cv2.idft(img_dft2)
magnitude2 = cv2.magnitude(img_combined2[:, :, 0],img_combined2[:, :, 1])
plt.figure()
plt.subplot(221)
plt.imshow(img1, cmap = 'gray')
plt.title('Mandrill Image')
plt.xticks([])
plt.yticks([])
plt.subplot(222)
plt.imshow(magnitude_spectrum11, cmap = 'gray')
plt.title('Magnitude Spectrum')
plt.xticks([])
plt.yticks([])
plt.subplot(223)
plt.imshow(phase_spectrum1, cmap = 'gray')
plt.title('Phase Spectrum')
plt.xticks([])
plt.yticks([])
plt.subplot(224)
plt.imshow(magnitude1, cmap = 'gray')
plt.title('Magnitude of Mandrill with Clowns Phase')
plt.xticks([])
plt.yticks([])
plt.show()

plt.figure()
plt.subplot(221)
plt.imshow(img2, cmap = 'gray')
plt.title('Clown Image')
plt.xticks([])
plt.yticks([])
plt.subplot(222)
plt.imshow(magnitude_spectrum22, cmap = 'gray')
plt.title('Magnitude Spectrum')
plt.xticks([])
plt.yticks([])
plt.subplot(223)
plt.imshow(phase_spectrum2, cmap = 'gray')
plt.title('Phase Spectrum')
plt.xticks([])
plt.yticks([])
plt.subplot(224)
plt.imshow(magnitude2, cmap = 'gray')
plt.title('Magnitude of Clown with Mandrills Phase')
plt.xticks([])
plt.yticks([])
plt.show()
# magnitude 1 for both images and their own phases
img_dft1 = np.zeros((256,256,2),dtype = np.float32)
img_dft1[:, :, 0], img_dft1[:, :, 1] = cv2.polarToCart(np.ones((256,256),dtype = np.float32),phase_spectrum1)
img_combined11 = cv2.idft(img_dft1)
magnitude111= cv2.magnitude(img_combined11[:, :, 0],img_combined11[:, :, 1])

img_dft2 = np.zeros((256,256,2),dtype = np.float32)
img_dft2[:, :, 0], img_dft2[:, :, 1] = cv2.polarToCart(np.ones((256,256),dtype = np.float32),phase_spectrum2)
img_combined22 = cv2.idft(img_dft2)
magnitude222 = cv2.magnitude(img_combined22[:, :, 0],img_combined22[:, :, 1])

plt.figure()
plt.subplot(121)
plt.imshow(magnitude111, cmap = 'gray')
plt.title('Mandrills Phase with magnitude 1')
plt.xticks([])
plt.yticks([])
plt.subplot(122)
plt.imshow(magnitude222, cmap = 'gray')
plt.title('Clowns Phase with magnitude 1')
plt.xticks([])
plt.yticks([])
plt.show()
